### PR TITLE
Walescot

### PR DESCRIPTION
**Pull request by ThomasMFNHS**
as discussed

### CODE REVIEW

**Comment by whg** [comment]
Do you just want to go ahead and put what's in `fake_sync.ts` into `sync.ts`?

Note that I renamed `guardian.ts` with `cases.ts` so you might just want to stick your functions in there?

Some pendantic & optional notes:

- Use `import` instead of `require()`

- Could you use `fetch` instead of `axios`? We already depend it and it does the same job. I know axios is great, but I like `node-fetch` because it means I only have to remember one API.

- I don't like the way you're mixing `await` with `then()`, use one or the other. So, either:

```js
export async function casesWales(): Promise<Cases> {
    return axios.get('https://www.livescience.com/wales-coronavirus-updates.html').then((response: { data: any }) => {
      // Load the web page source code into a cheerio instance
      const $ = cheerio.load(response.data)
      const rows = $('#article-body > ul > li')

    const output : Cases = {}
      for (let i = 0; i < rows.length; i++) {
          var text = ($(rows[i]).text()).split(':')
          if ((text[0] != 'Total') && (text[0] != 'Unknown location')) {
              output[text[0]] = parseInt(text[1].trim())
          }
      }
      return output
    })
}
```

or:

```js
export async function casesWales(): Promise<Cases> {
    const output : Cases = {}
    const response = await axios.get('https://www.livescience.com/wales-coronavirus-updates.html')
      // Load the web page source code into a cheerio instance
      const $ = cheerio.load(response.data)
      const rows = $('#article-body > ul > li')

      for (let i = 0; i < rows.length; i++) {
          var text = ($(rows[i]).text()).split(':')
          if ((text[0] != 'Total') && (text[0] != 'Unknown location')) {
              output[text[0]] = parseInt(text[1].trim())
          }
      }
    return output
}
```

I have been using the later in the repository so, it would be my preference!

(Sorry about the bad indentation!)

**Comment by ThomasMFNHS** [comment]
Hey,

Made those changes (except axios - couldn't figure out how to get the equivalent out of fetch).

Altered the functions so that the format out the output matched the new version for england - issue is that we don't get ids or population from the sources I was using. The id = name and pop = 0 for now

What are we actually using this data for?

Appreciate the notes btw!

**Comment by whg** [comment]
Great, no worries about axios.

Maia uses the data to look at which areas are in need, I think.

I've removed the population update for now, I think Maia put them in manually, so it would be a shame to set them to 0!

I know this might be painful for a Python guy, but could you set your indentation to 2 spaces for this project? I recommend using somekind of tslint in you editor to correct these things as you go. 

Also please spaces between the {: `{ merge: true }`, not `{merge:true}`

Thanks!

**Comment by ThomasMFNHS** [comment]
Cool - updated the indentations/ checked the merge: true spacing

Ha - the 2 spaces does look v strange to my eyes

Still struggling to actually run locally - I get asked for firebase config even when I have the .runtimeconfig.json sitting there - do you need to explicitly pass it?

**Pull request merged**
